import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import {Toaster} from 'sonner'

import Wrapper from "@/components/Wrapper";
import { AppWrapper } from "@/context";

import { AuthProvider } from "@/providers/AuthProvider";
import { ThemeProvider } from "next-themes";
import { LoadingProvider, useLoading } from "@/context/LoadingContext";

import Header from "@/components/Header";
import BottomNav from "@/components/BottomNav";
import GlobalLoader from "@/components/GlobalLoader"
import Footer from "@/components/Footer";
import ClothingCTA from "@/components/CTA";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className+ "bg-background dark:bg-background-dark"}>
        <AuthProvider>
        <AppWrapper>
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange>
          <LoadingProvider>
            <GlobalLoader/>
          <Wrapper path="/admin">
          <Header/>
          </Wrapper>
        <div className="text-text dark:text-text-dark w-full h-full text bg-background dark:bg-background-dark pt-[63.99px]">
          {children}
          <Wrapper path="/admin">
          <ClothingCTA />
          <Footer/>
          </Wrapper>
        </div>
        <Wrapper path="/auth">
        <BottomNav/>
        </Wrapper>
          <Toaster position="bottom-right"/>
          </LoadingProvider>

        </ThemeProvider>
        </AppWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}