import type { Metadata } from "next";
<<<<<<< HEAD
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
=======
import { Inter } from "next/font/google";
import { AppWrapper } from "@/context";
import "./globals.css";
import {Toaster} from 'sonner'
import {AuthProvider} from "./providers"


const inter = Inter({ subsets: ["latin"] });
>>>>>>> authenticationDemo/main

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
=======
      <body className={inter.className}>
        <AuthProvider>
        <AppWrapper>
        <div className="bg-white dark:bg-black">
          {children}
          <Toaster position="bottom-right"/>
        </div>
        </AppWrapper>
        </AuthProvider>
>>>>>>> authenticationDemo/main
      </body>
    </html>
  );
}
